branch-defaults:
  default:
    environment: aws-interface-dev
environment-defaults:
  aws-interface-dev:
    branch: null
    repository: null
global:
  application_name: aws-interface
  default_ec2_keyname: aws-interface
  default_platform: arn:aws:elasticbeanstalk:ap-northeast-2::platform/Python 3.6 running
    on 64bit Amazon Linux/2.8.3
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
